<details>
<summary>📂 Click to view all file and folder links</summary>

- [EZ-Flash Guide (Repo)](https://github.com/ChimeraGaming/EZ-Flash_Guide)
- [Docs Folder](https://github.com/ChimeraGaming/EZ-Flash_Guide/tree/main/Docs)
- [Directory Structure](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Docs/Directory_Structure.md)
- [Homebrew](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Docs/Homebrew.md)
- [Recommended Tools](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Docs/Recommended_Tools.md)
- [Save Guide](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Docs/Save.md)
- [Theme Files](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Docs/Theme_Files.md)
- [Setup](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Docs/Setup.md)
- [EZ Flash Jr Resources](https://github.com/ChimeraGaming/EZ-Flash_Guide/tree/main/Docs/EZ_Flash_Jr_Resources)
- [Models Folder](https://github.com/ChimeraGaming/EZ-Flash_Guide/tree/main/Models)
- [EZ-Flash Parallel (2023)](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Models/All_DS/2023_EZ-Flash_Parallel.md)
- [EZ-Flash Junior (2019)](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Models/GB/2019_EZ-Flash_Junior.md)
- [EZ-Flash Advance (2001)](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Models/GBA/2001_EZ-Flash_Advance.md)
- [EZ-Flash III (2005)](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Models/GBA/2005_EZ-Flash_III.md)
- [EZ-Flash IV (2005)](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Models/GBA/2005_EZ-Flash_IV.md)
- [EZ-Flash Reform (2017)](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Models/GBA/2017_EZ-Flash_Reform.md)
- [EZ-Flash Omega (2018)](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Models/GBA/2018_EZ-Flash_Omega.md)
- [EZ-Flash Omega DE (2021)](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Models/GBA/2021_EZ-Flash_Omega_Definitive_Edition.md)
- [Crystal Oscillator Fix](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Troubleshooting/Crystal_Oscillator_Failure_No_Nintendo_Logo_Fix.md)
- [RTC Troubleshooting](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Troubleshooting/Real_Time_Clock.md)
- [Troubleshooting Index](https://github.com/ChimeraGaming/EZ-Flash_Guide/tree/main/Troubleshooting)
- [Cheats](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Tutorials/Cheats.md)
- [Creating Themes](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Tutorials/Creating_Themes.md)
- [Editing Save Files](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Tutorials/Editing_Save_Files.md)
- [Tutorials Index](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Tutorials/README.md)
- [Creating Thumbnails](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Tutorials/Creating_Thumbnails.md)
- [ROM Dumping and Patching](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/Tutorials/ROM_Dumping_and_Patching.md)
- [Main README](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/README.md)
- [License](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/LICENSE)
- [FAQ](https://github.com/ChimeraGaming/EZ-Flash_Guide/blob/main/FAQ.md)

</details>
